### ISSUE TITLE
Filepath issue

### ISSUE THREAD

**Issue by interception123** [phtdacosta/windows-shortcut-maker#1]
20 line 
`if (isString(options.lnkIco) === false) options.lnkIco = filepath`
But should be
`if (isString(options.lnkIco) === false) options.lnkIco = options.filepath`
Or it won't work at all
P.S. I'm newbie to all this git things and can't create pull request

**Comment by phtdacosta** [comment]
Thank you so much for pointing out this mistake!! I will be correcting it today and will upload the version as soon as I update the code. If you ever find another issue or think about any improvement, I would be glad to hear.
